package org.Games.model.game;

public enum GameState {
    INITPLAYER,
    FINISHED,
    DISPLAYBOARD,
    MOVE,
    CHECKFINISH,
    ASKPLAYER,
    CHECKPLAYER,
    IAMOVE,
    INITGAME,
    CHECKSAVE,
    ASKFORCHOSEGAME,
    CREATETICTACTOE,
    CREATEGOMOKU,
    CREATEPOWER4,
    ASKTORESTOREGAME,
    SHOWBOARD,
    DISPLAYPLAYER,
    ASKFORCHOSENUMBEROFPLAYER,
    DISPLAYONLYBOARD,
    MAIN,
    INVALIDINPUT,
    ASKFORROW,
    SHOWINPUT, ASKFORCOL
}
